name: Build gpu-capacity-exporter

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Format chack
        run: |
          mvn formatter:validate

      - name: Test with Maven
        run: |
          mvn test

      - name: Login to OCI Container Registry
        uses: docker/login-action@v3
        with:
          registry: nrt.ocir.io
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:1.0.2
        env:
          IMAGE: nrt.ocir.io/orasejapan/shukawam/gpu-capacity-exporter
