name: Build gpu-capacity-exporter

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve # of images in some repo in a compartment
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-images
        with:
          silent: False
          command: 'artifacts container repository list --compartment-id ocid1.compartment.oc1..aaaaaaaanjtbllhqxcg67dq7em3vto2mvsbc6pbgk4pw6cx37afzk3tngmoa'
          query:  'data.items[*]."display-name"'
